### ISSUE TITLE
How do I disable the content pane and filter when using the <ngx-powerbi-component> component?

### ISSUE THREAD

**Issue by peterkd** [ramandeep-singh-1983/ngx-powerbi#11]
Hello,

I'm using the ngx-powerbi-component as below. Question: how do I pass the filterPaneEnabled and navContentPaneEnabled parameters to it ?

Thanks !

ngx-powerbi-component type="report"
                           id="..."
                           embedUrl="https://app.powerbi.com/...."
                           tokenType="embed"
                           accessToken="token"
    ngx-powerbi-component

**Comment by peterkd** [comment]
Figured it out - use "options"...

**Comment by animeshrajurkar** [comment]
@peterkd, it would be great if you can post the "options" sample for the benefit of other users. Thanks!

**Comment by ingarhillestad** [comment]
@peterkd I'm not getting the "options" part to work... Care to share you're findings?
