### ISSUE TITLE
Destroy Report

### ISSUE THREAD

**Issue by roffus** [ramandeep-singh-1983/ngx-powerbi#15]
Hello,
is there a way to destroy, or reset a report?

**Comment by ramandeep-singh-1983** [comment]
The Power BI service provides a reset() method, refer https://github.com/Microsoft/PowerBI-JavaScript/wiki/Service-Details for details. Also, refer the APIs exposed by the Power BI service here: https://github.com/ramandeep-singh-1983/ngx-powerbi/blob/master/projects/ngx-powerbi/src/lib/ngx-powerbi.service.ts

**Comment by kamalendu-cts** [comment]
Hello,
Can anybody help me on 
1) How to pass filter parameter in ngx-powerbi?
2) and how we get List of KPIs in ngx-powerbi?

**Comment by ramandeep-singh-1983** [comment]
Closing due to lack of reply from originator.
