### ISSUE TITLE
How to get PowerBI access Token

### ISSUE THREAD

**Issue by satsangswami** [ramandeep-singh-1983/ngx-powerbi#19]
I have a Power BI Pro, account. I have tried many ways, but doesn't know how to get the Access Token... Whats the easiest way to get it. I don't know c# or web api properly. NodeJS Express is fine for me. Please let me know from where do i get AccessToken

**Comment by ramandeep-singh-1983** [comment]
If you refer my medium article about it (https://medium.com/@ramandeep.singh.1983/power-bi-overview-and-angular-embedding-how-to-f73390f4a399) and this gist: https://gist.github.com/ramandeep-singh-1983/0350b22130884ecefdb54f41a92ba232, you can see how an access token can be generated. Basically, an access token can't be generated through the JavaScript SDK or ngx-powerbi library. It can only be generated through the backend NodeJS API.

There was a NodeJS SDK for Power BI (https://github.com/Microsoft/PowerBI-Node) but it has been depreciated now. Other options are:
Python: https://community.powerbi.com/t5/Developer/access-token-power-bi-python/m-p/350405
REST API: https://docs.microsoft.com/en-gb/rest/api/power-bi/embedtoken

**Comment by ramandeep-singh-1983** [comment]
closed due to inactivity.
