### ISSUE TITLE
Report Mobile Layout

### ISSUE THREAD

**Issue by alefFSilva** [ramandeep-singh-1983/ngx-powerbi#2]
Hello !

It's possible to render report mobile version?

Thank you

**Comment by ramandeep-singh-1983** [comment]
I haven't checked that but now I will and will report back soon, hold tight!

**Comment by ramandeep-singh-1983** [comment]
The mobile version rendering is part of the Power BI dashboard or report itself. In Power BI desktop, you can customize the UI for mobiles. The library should work fine for both desktop and mobile.

Let me know if that answers you question.

**Comment by alefFSilva** [comment]
Great !

Thank you !
