### ISSUE TITLE
Caching doesn't work for PowerBI Reports

### ISSUE THREAD

**Issue by Kumar-Aakash** [ramandeep-singh-1983/ngx-powerbi#20]
Hi,

Thank you for the amazing library.

This is my scenario:

I have a dashboard in the angular application which is showing n number of Tiles of different sizes, let's say 6 or 7. In each Tile, I am loading PowerBI reports designed for these tiles. All good till here.

If I switch back tabs on the application and come back to the dashboard, it repeats the process again and fetches reports again.

Is there any way I can apply cache or store reports so that the second time, it doesn't load reports freshly.

I tried with the this library but couldn't do it.

One request, even if it is out of scope from the usage of this amazing library, what could be the approach to solve it. So Application with multiple tiles with this behavior will not deliver a good UX. 

Thanks again.

**Comment by ramandeep-singh-1983** [comment]
@aakash1401, thanks for your kind comments :)
This is indeed out of scope of this library. But i can give a pointer which can help with this: https://itnext.io/cache-components-with-angular-routereusestrategy-3e4c8b174d5f

This will prevent reload of the component while switching tabs.

**Comment by ramandeep-singh-1983** [comment]
Closing issue due to lack of response (answer already posted above)
