### ISSUE TITLE
ngx-component options

### ISSUE THREAD

**Issue by afviola** [ramandeep-singh-1983/ngx-powerbi#22]
Hello,

I'm using the ngx-powerbi-component as below. Question: how do I pass the filterPaneEnabled and navContentPaneEnabled parameters to it?

`<ngx-powerbi-component type="
  id="..."
  embedUrl="https://app.powerbi.com/...."
  tokenType="embed"
  accessToken="token"
</ngx-powerbi-component>`

Thanks!

**Comment by ramandeep-singh-1983** [comment]
@afviola, you are using method 1 as per the readme. You need to use method 2 or 3 as mentioned in the readme for configuring the said options.

**Comment by afviola** [comment]
I did the following to make it work:

`<ngx-powerbi-component
  [type]="type"
   [id]="id"
   [embedUrl]="embedUrl"
   [tokenType]="tokenType"
   [accessToken]="accessToken"
   on-embedded="onEmbedded($event)"
   [options]="options">
<ngx-powerbi-component>`

// page.ts
  options = {
      filterPaneEnabled: false,
      navContentPaneEnabled: false
  };

Thank you so much for this library!

**Comment by ramandeep-singh-1983** [comment]
Thanks for updating about the status of your issue!
