### ISSUE TITLE
report.on('loaded'... doesnt executes

### ISSUE THREAD

**Issue by lucaspein** [ramandeep-singh-1983/ngx-powerbi#24]
Hello!

I just copied the code from an old issue and modified my code.

This is my Angular 7 component

import { Component, OnInit } from '@angular/core';
import { EnvironmentService } from '../../environments/service/environment.service';
import { NgxPowerBiService } from 'ngx-powerbi';
import { Page } from 'page';
import { Report } from 'report';
import { Dashboard } from 'dashboard';
import { IEmbedConfiguration } from 'embed';
import { TokenType, Permissions} from 'powerbi-models';

@Component({
  selector: 'app-powerbi',
  templateUrl: './powerbi.component.html',
  styleUrls: ['./powerbi.component.css']
})
export class PowerbiComponent implements OnInit {
    private powerBiService: NgxPowerBiService;
    private pbiContainerElement: HTMLElement;
    height = 90;
    width = 90;
    url = '';
    key = '';

    constructor(environmentService: EnvironmentService) {
        this.height = window.innerHeight - 69;
        this.width = window.innerWidth;
        this.url = environmentService.configuration.PowerbiUrl;
        this.key = environmentService.configuration.PowerbiKey;
        this.powerBiService = new NgxPowerBiService();

    }
   

    ngOnInit() {
        this.pbiContainerElement = <HTMLElement>(document.getElementById('pbi-container'));
              

        var config: IEmbedConfiguration = {
            type: 'report',
            tokenType: TokenType.Aad,            
            accessToken: this.key,
            embedUrl: this.url,
            id: 'f6bfd',
            pageName:'Tenants History',
            permissions: Permissions.All,
            settings: {
                filterPaneEnabled: true,
                navContentPaneEnabled: true
            }
        };

        const report: Report = <Report>this.powerBiService.embed(this.pbiContainerElement, config);

        // Now all 'report' object APIs should work
        report.on('loaded', function (event): any {
            report.getPages().then((pages)=> {
                console.log('report loaded, number of pages: ', pages.length);
                // We only want to handle the 'loaded' event once
                report.off('loaded');
            });
        });
        
  }

}

If i put a breakpoint in it doesnt executes!

ThankU!!

**Comment by ramandeep-singh-1983** [comment]
I would suggest to put questions on stackoverflow as lot of users can help you there. I am not actively working on this these days so it becomes a bit difficult for me to answer the queries.

**Comment by ramandeep-singh-1983** [comment]
Closed due to non-activity
