### ISSUE TITLE
Please, provide a example of OPTIONS

### ISSUE THREAD

**Issue by maubuso** [ramandeep-singh-1983/ngx-powerbi#25]
Hi, I´m using you excelent component.

I use the ngx-power-bi-component because i need to pass some parameters. On DIV version I can´t.

I need to understand how option works on ngx-power-bi-component to hide panel filter. 

Can you post some examples, please? Thanks !

**Comment by ramandeep-singh-1983** [comment]
I would suggest to put questions on stackoverflow as lot of users can help you there. I am not actively working on this these days so it becomes a bit difficult for me to answer the queries.

Regarding your specific query, please refer the README.md file of this library and specifically method 2, you will find this there:

`powerbi-settings-filter-pane-enabled="false"`

**Comment by ramandeep-singh-1983** [comment]
Response already provided. Closed due to non-activity
