### ISSUE TITLE
report. print() don't appear

### ISSUE THREAD

**Issue by Prata1** [ramandeep-singh-1983/ngx-powerbi#27]
I like do know if can insert in the lib function to print the report

**Comment by ramandeep-singh-1983** [comment]
I would suggest to put questions on stackoverflow as lot of users can help you there. I am not actively working on this these days so it becomes a bit difficult for me to answer the queries.

Regarding your query: you need to have an object of type "Report" and the print() method is available for the same. If your object is of type "Embed", you will need to type cast it into "Report" type. I have already used it in the app and it works fine. More details here: https://github.com/microsoft/PowerBI-JavaScript/wiki/Embedding-Basic-interactions#print-a-report

**Comment by ramandeep-singh-1983** [comment]
Closed due to non-activity
