### ISSUE TITLE
Cannot build with Angular Universal

### ISSUE THREAD

**Issue by vincent** [ramandeep-singh-1983/ngx-powerbi#3]
Hi, thanks for the lib.

I'm building an Angular Universal app, but the `npm run serve` failed with 
```
> project@0.0.0 serve:ssr .../project
> node dist/server

.../project/dist/server.js:137568
		        this.receiveWindow = options.receiveWindow || window;
		                                                      ^
ReferenceError: window is not defined
    at new WindowPostMessageProxy (.../project/dist/server.js:137568:57)
    at exports.wpmpFactory (.../project/dist/server.js:137465:13)
    at new Service (.../project/dist/server.js:132724:22)
    at Object.<anonymous> (.../project/dist/server.js:132688:16)
    at __webpack_require__ (.../project/dist/server.js:132634:30)
    at .../project/dist/server.js:132654:18
    at .../project/dist/server.js:132657:10
    at webpackUniversalModuleDefinition (.../project/dist/server.js:132612:20)
    at Object.<anonymous> (.../project/dist/server.js:132614:3)
    at __webpack_require__ (.../project/dist/server.js:20:30)
```

I assume it's because when your module [instanciate the pbiService](https://github.com/ramandeep-singh-1983/ngx-powerbi/blob/master/src/lib/ngx-powerbi.service.ts#L29), the code behind use `window`, as [in here](https://github.com/Microsoft/PowerBI-JavaScript/blob/master/dist/powerbi.js#L4975)

Did you encountered this issue already, or do you have any hints to work around it ?

Regards,

**Comment by ramandeep-singh-1983** [comment]
Hi Vincent, thanks for using the library. 
Looks like you are doing server side rendering with Angular Universal. I haven't tested this part yet as i only developed and tested this for a client side Angular app.

I will try to find some time and check this out soon. I also need to create a sample app that uses this library.

**Comment by vincent** [comment]
No worries.
You can find the official angular universal demo app [here](https://angular.io/guide/universal), if needed.

**Comment by vincent** [comment]
The problem seems to come from `powerbi-client` [actually](https://github.com/Microsoft/PowerBI-JavaScript/blob/master/dist/powerbi.js#L85), so it's possible you couldn't do much about it :/

**Comment by ramandeep-singh-1983** [comment]
ah yes, i am just using the JavaScript service directly so it's a simple TypeScript wrapper class over the JavaScript class. Can you log a defect in the powerbi-client repo for this scenario?

**Comment by vincent** [comment]
I can't, because they want us to use their paid support.

For any future visitor, here is my workaround for now

- include `node_modules/powerbi-client/dist/powerbi.js` in `angular.json` in the front build scripts section
- test the platform before calling the raw powerbi-client library
```ts
@ViewChild('embedContainer') embedContainer: ElementRef;

constructor( @Inject(PLATFORM_ID) private platformId: string ) {}

ngOnInit() {
  if (isPlatformBrowser(this.platformId)) {
    const models = window['powerbi-client'].models;
    this.currentEmbed = window['powerbi'].embed(embedContainer.nativeElement, config);
  }
}
```
