### ISSUE TITLE
Filter pane hiding

### ISSUE THREAD

**Issue by bmnyc0923** [ramandeep-singh-1983/ngx-powerbi#30]
Hi ,
Ive been using your library from past 6 months to embed powerbi report into angular application . in our powerbi report i hide the filterpane and publish . it used to work fine when we embed too . filter pane used to be hidden . i dont know why but from this week even though the filter pane is hidden in the report . it shows up in the embedded report . i tried even this thing like adding &filterPaneEnabled=false .it doesnt work too . but when i pin my report to a live page . the filter pane is hidden as expected so i believe something has changed ? 
Any help would be appreciated 
keep up the great work 

Thankyou

**Comment by ramandeep-singh-1983** [comment]
This should be an issue in Microsoft's powerbi-client javascript library as ngx-powerbi is just a TypeScript wrapper on top of it. I would suggest you to raise this issue in powerbi-client github repo.
