### ISSUE TITLE
Angular version compatibility

### ISSUE THREAD

**Issue by munibabuc** [ramandeep-singh-1983/ngx-powerbi#37]
my current version of angular project is 9.x.x but i am trying to upgrade 11.
Getting compatibility issues with ngx-powerbi

Package "ngx-powerbi" has an incompatible peer dependency to "@angular/common" (requires "^9.1.2" (extended), would install "11.0.7").

Is there anyway to upgrade my project or do i need wait for next release of ngx-pwerbi package.

**Comment by ramandeep-singh-1983** [comment]
Version 4.0.0 has been released for Angular 13.

**Comment by backtracker-rj** [comment]
Is there any ngx-powerbi version that is compatible with Angular 11 and 12?
Version 3&4 are not compatible.
