### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by anotherkhan** [ramandeep-singh-1983/ngx-powerbi#4]
Hi, Thanks for sharing the wrapper.

I am new to angular and I am using angular 5 for my app. when building the project I am getting following error:

WARNING in ./node_modules/ngx-powerbi/fesm5/ngx-powerbi.js
263:59-75 "export 'defineInjectable' was not found in '@angular/core'

here is my package.json 

{
  "name": "rebar-spa-v2-template",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve -p 9091 -o",
    "build": "ng build --prod --named-chunks",
    "test": "ng test --code-coverage",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "code-scan": "retire --ignorefile .retireignore -p --severity high --nocache -v "
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.11",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "angular-oauth2-oidc": "^3.1.4",
    "bootstrap": "4.1.0",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "ngx-powerbi": "^1.0.4",
    "powerbi-client": "^2.6.0",
    "rxjs": "^5.5.6",
    "tether": "1.4.0",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.8",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3",
    "ngx-cookie-service": "^1.0.10",
    "karma-junit-reporter": "^1.2.0",
    "karma-mocha-reporter": "^2.2.3",
    "retire": "^1.6.0"
  }
}

Thanks.

**Comment by ramandeep-singh-1983** [comment]
The library has been built using Angular 6 and uses the new Angular 6 way of injecting stuff so it's possible that you will see issues with Angular 5. If possible, can you update your stuff to Angular 6?

**Comment by anotherkhan** [comment]
Thanks for your response, I was able to migrate the app to angular 6 and the library works beautifully!
