### ISSUE TITLE
Angular 13 compatibility

### ISSUE THREAD

**Issue by a-martynov** [ramandeep-singh-1983/ngx-powerbi#53]
Please add Angular 13 compatibility. Now its only possible with npm install --force

**Comment by AmGarera** [comment]
I've submitted the PR here for it #60

**Comment by a-martynov** [comment]
Thanks. My team already chose another package for BI : powerbi-client-angular

**Comment by ramandeep-singh-1983** [comment]
Closing ticket as version 4.0.0 of the library with Angular 13 has been released today. Kindly test and raise a new ticket if it doesn't work.
