### ISSUE TITLE
Angular 14 is not supported

### ISSUE THREAD

**Issue by bjorn-einar-bjartnes-4ss** [ramandeep-singh-1983/ngx-powerbi#66]
Package version seems to be locked to angular 13. 
I can look at making a version that is compatible with angular 14, like with https://github.com/ramandeep-singh-1983/ngx-powerbi/pull/60
This should be an easier upgrade, though, I just wanted to discuss it in an issue before making the PR.

I am not that deep into angular and versioning, but was wondering if it would help to make a package version strategy that is locked to angular versioning? Currently ngx-powerbi 3 was locked to v9 of angular and ngx-powerbi 4 was locked to angular 13, so it would perhaps make more sense to make ngx-powerbi 14 locked to angular 14? Or should a "looser" form of strategy be enabled where package versions have a more liberal coupling to angular major versions?

**Comment by bjorn-einar-bjartnes-4ss** [comment]
PR is merged, but not pushed to npm https://www.npmjs.com/package/ngx-powerbi

**Comment by ramandeep-singh-1983** [comment]
Just pushed it to npm.

**Comment by bjorn-einar-bjartnes-4ss** [comment]
Edited the comment, it was the wrong way around, I need to upgrade angular to a new minor version only. Sorry :)

**Comment by bjorn-einar-bjartnes-4ss** [comment]
Yay - with some other changes I could get rid of --legacy-peer-deps 👯‍♂️
