### ISSUE TITLE
report.fullscreen() doesn't work

### ISSUE THREAD

**Issue by marian-gheorghe** [ramandeep-singh-1983/ngx-powerbi#7]

**Comment by marian-gheorghe** [comment]
`this.powerBiService.embed(pbiContainerElement, config).fullscreen()` doesn't seem to work (no display change noticed)

**Comment by marian-gheorghe** [comment]
you can close this one as well, problem fixed after casting the result of the embed function from `Embed `to `Report `object (which extends an `Embed`)

**Comment by ramandeep-singh-1983** [comment]
Closed as the solution has been given in the above post.
